### ISSUE TITLE
js-yaml contains an issue with dumping strings starting with 0 and containing 8 or 9

### ISSUE THREAD

**Issue by Hallian** [ovatto/cfbuild#10]
js-yaml contains an issue with dumping strings startings with 0 and containing 8 or 9.

Steps to reproduce:

Test template:
```
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DevelopmentStack:
    Type: List
    Default:
      - '00004'
      - '00059'
```

Run `cfbuild template -t test-template.yaml -o built_template.yaml`

Expected result:
```
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DevelopmentStack:
    Type: List
    Default:
      - '00004'
      - '00059'
```

Actual result:
```
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DevelopmentStack:
    Type: List
    Default:
      - '00004'
      - 00059
````

This issue can be fixed by upgrading to js-yaml. This work has been done in PR #9
